MOVE-2691 adding actuator endpoint and bumping snapshot
felleslosninger/efm-statistics-client pull request #7
Opened 2022-05-04 06:57 UTC by jaflaten

2022-05-04 07:01 UTC, FrodeBjerkholt approved these changes

2022-05-04 11:12 UTC, martinwam requested changes

2022-05-04 11:12 UTC, martinwam commented on src/main/java/no/digdir/efmstatisticsclient/config/SecurityConfig.java
> +                .and().build();
return http.securityMatcher(ServerWebExchangeMatchers.anyExchange())
                .cors().and().csrf().disable()
                .authorizeExchange(c -> c.pathMatchers("/actuator/**").permitAll()
                        .anyExchange().authenticated())
                .httpBasic().and().build();

2022-05-11 08:21 UTC, martinwam commented on pom.xml
> +        <move-common.version>1.8.0</move-common.version>
Er ikke typ 1.15.0 siste?

2022-05-11 08:21 UTC, martinwam commented on pom.xml
> +<!--        <dependency>-->
Bort?

2022-05-11 08:21 UTC, martinwam commented on pom.xml
> +<!--        <dependency>-->
Bort?

2022-05-11 08:40 UTC, martinwam approved these changes

2022-05-11 08:42 UTC, merged